export const USER = [
  {
    id: 383,
    name: "Yaarb",
    email: "yaarb@gmail.com",
    password: "123",
    status: "Alive",
    species: "Alien",
    type: "",
    gender: "Male",
    origin: {
      name: "unknown",
      url: "",
    },
    location: {
      name: "St. Gloopy Noops Hospital",
      url: "https://rickandmortyapi.com/api/location/16",
    },
    image: "https://rickandmortyapi.com/api/character/avatar/383.jpeg",
    episode: ["https://rickandmortyapi.com/api/episode/19"],
    url: "https://rickandmortyapi.com/api/character/383",
    created: "2018-01-10T19:48:59.952Z",
    roles: ["admin", "manager", "staff"],
  },
  {
    id: 426,
    name: "Greasy Grandma",
    email: "greasyGrandma@gmail.com",
    password: "123",
    status: "Alive",
    species: "Human",
    type: "Grandma",
    gender: "Female",
    origin: {
      name: "Greasy Grandma World",
      url: "https://rickandmortyapi.com/api/location/73",
    },
    location: {
      name: "Greasy Grandma World",
      url: "https://rickandmortyapi.com/api/location/73",
    },
    image: "https://rickandmortyapi.com/api/character/avatar/426.jpeg",
    episode: ["https://rickandmortyapi.com/api/episode/10"],
    url: "https://rickandmortyapi.com/api/character/426",
    created: "2018-04-16T21:51:21.379Z",
    roles: ["manager", "staff"],
  },
  {
    id: 655,
    name: "Heroine Keith",
    email: "HeroineKeith@gmail.com",
    password: "123",
    status: "Alive",
    species: "Human",
    type: "",
    gender: "Male",
    origin: {
      name: "Near-Duplicate Reality",
      url: "https://rickandmortyapi.com/api/location/104",
    },
    location: {
      name: "Merged Universe",
      url: "https://rickandmortyapi.com/api/location/103",
    },
    image: "https://rickandmortyapi.com/api/character/avatar/655.jpeg",
    episode: ["https://rickandmortyapi.com/api/episode/39"],
    url: "https://rickandmortyapi.com/api/character/655",
    created: "2020-08-13T11:17:47.228Z",
    roles: ["staff"],
  },

  {
    id: 579,
    name: "Snake with Legs",
    email: "SnakeWithLegs@gmail.com",
    password: "123",
    status: "Alive",
    species: "Animal",
    type: "Snake",
    gender: "Male",
    origin: {
      name: "Snake Planet",
      url: "https://rickandmortyapi.com/api/location/78",
    },
    location: {
      name: "Snake Planet",
      url: "https://rickandmortyapi.com/api/location/78",
    },
    image: "https://rickandmortyapi.com/api/character/avatar/579.jpeg",
    episode: ["https://rickandmortyapi.com/api/episode/36"],
    url: "https://rickandmortyapi.com/api/character/579",
    created: "2020-05-07T12:22:08.800Z",
    roles: ["staff"],
  },
];
